### ISSUE TITLE
Which model support "multiclass" task

### ISSUE THREAD

**Issue by astrung** [DataCanvasIO/DeepTables#77]
<em>Please make sure that this is a feature request.</em>

**System information**
- DeepTables version: 0.2.3.1
- Are you willing to contribute it: No

**Describe the feature and the current behavior/state.**
When i test with various models in ModelConfig by change `nets=['fibi_nets']`, I see some model only support for binary classification, and when I tried to use with multi classification, I always get this error: `ValueError: Unexpected logit output.{}`

So how can I know which model support for multi classification, and which model is only for binary ?
Please help

**Comment by oaksharks** [comment]
Hi @astrung, 
Is there any categorical features in your dataset?
If not, you can set `auto_discrete=True` to discretize continuous features into categorical.
I think the network needs categorical features rather than does not support multi-classification.

References:
https://github.com/DataCanvasIO/DeepTables/blob/a95f842918351fd1875263490bdddb919de75b20/deeptables/models/deepnets.py#L338-L350

**Comment by astrung** [comment]
@oaksharks 
thank you for your fast response.
Yes after setting `auto_discrete=True`, my code works, but I get too many below warnings:

    /opt/conda/lib/python3.7/site-packages/sklearn/preprocessing/_discretization.py:233: UserWarning: Bins whose width are 
    too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins. 
    "decreasing the number of bins." % jj

How can I fix it ? Do I have problem in my features ?

**Comment by oaksharks** [comment]
Maybe the value of your features is too small, here is how DT calculates the number of the bins:
https://github.com/DataCanvasIO/Hypernets/blob/7b486d0a9206181d4f08f502160f8d6ba3a4994b/hypernets/tabular/sklearn_ex.py#L727-L737
